version: '3.8'

services:
  banking-dashboard:
    build:
      context: .
      dockerfile: docker-files/Dockerfile  # ✅ Correct path to the Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped